default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  host: <%= ENV["APP_GARAGE_DATABASE_HOST"] %>
  username: <%= ENV["APP_GARAGE_DATABASE_USERNAME"] %>
  password: <%= ENV["APP_GARAGE_DATABASE_PASSWORD"] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: app_garage_development
test:
  <<: *default
  database: app_garage_test
production:
  url: <%= ENV['DATABASE_URL'] %>
